# Generated by Django 5.2.1 on 2025-05-15 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Monitor', 'Monitor'), ('Teclado', 'Teclado'), ('Mouse', 'Mouse'), ('CPU', 'CPU'), ('Impressora', 'Impressora'), ('Outro', 'Outro')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_patrimonio', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Estoque', 'Estoque'), ('Em uso', 'Em uso'), ('Manutenção', 'Manutenção'), ('Com defeito', 'Com defeito')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alocacao', models.DateField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.responsavel')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.sala')),
            ],
        ),
    ]
